### ISSUE TITLE
Training / inference time?

### ISSUE THREAD

**Issue by ClaraBing** [fabienbaradel/object_level_visual_reasoning#2]
Hi Fabien,

May I ask for the average training and inference time of an iteration with batch size 8, and what GPU did you use?

Thank you very much!

**Comment by fabienbaradel** [comment]
Hi Clara, thanks for your interest. Since we run Mask-RCNN before training/testing our model the inference time is not very relevant. Below are the number without Mask-RCNN time.
Training is split into two steps: first training the object head and then training the full model.
Training the object head takes 55 minutes per epoch (10 epochs with batch of size 32 - ~1.2 sec per batch). Training the full model takes more time: 2:12 per epoch (10 epochs with batch of size 8 - ~0.750 per batch).
Testing our model on the full testing set (~28'000 videos) takes 26 minutes with a batch of size 16 (1 clip per video) so it is ~0.890 sec for 16 clips of 4 frames each.
The above results are with a Resnet50-like network as the backbone model.
I have run my experiments on a Titan XP and with a single GPU.
I hope it helps.

**Comment by ClaraBing** [comment]
Thank you so much for the detailed reply! This is very helpful ^ ^
